In [5]:
import torch

torch.cuda.is_available()

False

In [12]:
randint = torch.randint(-100,100, (2,3))
randint

tensor([[-63,  81,  66],
        [-43, -64, -63]])

In [14]:
torch_tensor = torch.Tensor(randint)
torch_tensor

tensor([[-63,  81,  66],
        [-43, -64, -63]])

In [18]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [20]:
ones = torch.ones(2,3)
ones

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [55]:
input_ = torch.empty(2,3)
input_

tensor([[7.0264e-18, 4.5902e-41, 7.0264e-18],
        [4.5902e-41, 4.4842e-44, 0.0000e+00]])

In [59]:
range_ = torch.arange(1, 12, 2)
range_

tensor([ 1,  3,  5,  7,  9, 11])

In [64]:
linspace = torch.linspace(1,100, steps=5)
linspace

tensor([  1.0000,  25.7500,  50.5000,  75.2500, 100.0000])

In [67]:
logspace = torch.logspace(1,10, steps=5)
logspace

tensor([1.0000e+01, 1.7783e+03, 3.1623e+05, 5.6234e+07, 1.0000e+10])

In [68]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [76]:
a = torch.empty(2,3, dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like

tensor([[    140690831023536,     140690831023536, 3543544772460421664],
        [4194312865637870896, 3473452022965613107, 2318265678939828275]])

In [152]:
import torch
import numpy as np
import time

In [153]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

In [169]:
%%time # as you can see the analysis in the second and third line in the output, it is done with this line

start_time = time.time()
zeros = torch.zeros(10,10)
end_time = time.time()

elapsed_time = end_time - start_time
print(elapsed_time)

9.918212890625e-05
CPU times: user 193 µs, sys: 48 µs, total: 241 µs
Wall time: 223 µs


In [174]:
probabilities = torch.tensor([0.2,0.2,0.6])

samples = torch.multinomial(probabilities, num_samples=10, replacement=True)
print(samples)

# probability of getting 0 => 20%, 1 => 20%, 2 => 80%

tensor([1, 0, 2, 0, 2, 2, 2, 2, 0, 2])


In [176]:
# concatination

tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim=0)
out

tensor([1, 2, 3, 4, 5])

In [177]:
out = torch.tril(torch.ones(5,5))
out

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [178]:
out = torch.triu(torch.ones(5,5))
out

tensor([[1., 1., 1., 1., 1.],
        [0., 1., 1., 1., 1.],
        [0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1.],
        [0., 0., 0., 0., 1.]])

In [190]:
# make a matrix of ones and them make it upper triangle and then fill the zeros with '-inf' and later apply this mask on the original matrix
out = torch.zeros(5,5).masked_fill(torch.tril(torch.ones(5,5)) == 0, float('-inf'))
out

tensor([[0., -inf, -inf, -inf, -inf],
        [0., 0., -inf, -inf, -inf],
        [0., 0., 0., -inf, -inf],
        [0., 0., 0., 0., -inf],
        [0., 0., 0., 0., 0.]])

In [191]:
torch.exp(out)

tensor([[1., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0.],
        [1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1.]])

In [202]:
# Suppose you have a tensor with the shape (A, B, C). If you perform a transpose operation with (0, 2), 
# the dimensions will be reordered as (C, B, A). So, the original dimension 0 becomes the new dimension 2, 
# and the original dimension 2 becomes the new dimension 0. The dimensions in between stay the same.

input_ = torch.zeros(2,3,4)
out = input_.transpose(0,2)
out.shape

torch.Size([4, 3, 2])

In [205]:
tensor1 = torch.tensor([1,2,3])
tensor2 = torch.tensor([4,5,6])
tensor3 = torch.tensor([7,8,9])

stacked_tensor = torch.stack([tensor1, tensor2, tensor3])
stacked_tensor

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [206]:
import torch.nn.functional as F

tensor1 = torch.tensor([1.0,2.0,3.0])

softmax_output = F.softmax(tensor1, dim=0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])
